name: Build und Deploy der Site

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Cecil
        uses: Cecilapp/Cecil-Action@v3
        with:
          config: 'cecil.yml'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: 'site-content'
          path: '_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.2          
        with:
          name: 'site-content'

      - name: Connect
        id: connect
        uses: danhendrickson/sftp-transfer-action@v1.23
        with:
          server: home13399339.1and1-data.host
          user: ${{ secrets.FTP_USER_IONOS }}
          pass: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local-path: '.'
          remote-path: '.'

      - name: Transfer Status
        run: echo "Transfer Status - ${{ steps.connect.outputs.transferStatus }}"
